### ISSUE TITLE
Javascript Feedback

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/whats-yo-name#1]
Hi @thomasjbradley! 

Just started your Javascript lessons; when I get through them, can I get access to an answer key (similar to how we did things for WebDev 1)? Or, if not, can I get feedback on my construction of JS code as I go along?

Also, I saw workshops posted; are those in-person sessions, or solely self-directed?

Cheers!

MacKenzie Bulkowski-Rose

**Comment by thomasjbradley** [comment]
I’m happy to give you access to all the solutions when you’re done.
And you’re welcome to get feedback as you’re going through the course—just create an Issue whenever you want feedback.

The workshops are in-person sessions. I just finalized the dates earlier this week. I haven’t even announced them to the 2nd years yet. They will be:

- Tues., Feb. 26 — 2–5 @ N208
- Tues., Mar. 5 — 2–5 @ N208
- Tues., Mar. 12 — 2–5 @ N208

You’re welcome to attend!

**Comment by MacKenzieRose** [comment]
Thanks so much; I would love to attend.

Cheers!

MacKenzie
